inheritedBy:
  language: typescript
  layer: library

fileGroups:
  configs:
    - "*.config.ts"
    - "*.json"
  sources:
    - "src/**/*"

tasks:
  build:
    command: "bun run build"
    inputs:
      - "@group(configs)"
      - "@group(sources)"
    outputs:
      - "dist"

  dev:
    command: "bun run dev"
    preset: "server"
    inputs:
      - "@group(configs)"
      - "@group(sources)"

  typecheck:
    command: "bun run typecheck"
    inputs:
      - "@group(configs)"
      - "@group(sources)"
