inheritedBy:
  language: rust

fileGroups:
  configs:
    - "Cargo.toml"
  sources:
    - "src/**/*"

tasks:
  build:
    command: cargo
    args: ["build"]
    inputs:
      - "@group(configs)"
      - "@group(sources)"
      - "/Cargo.lock"
    outputs:
      - "/target/debug/luna"
      - "/target/debug/lna"

  install:
    command: cargo
    args: ["install", "--path", ".", "--locked", "--force"]
    deps:
      - "~:build"
    inputs:
      - "@group(configs)"
      - "@group(sources)"
      - "/Cargo.lock"
    options:
      cache: false

  test:
    command: cargo
    args: ["test"]
    deps:
      - "~:build"
    inputs:
      - "@group(configs)"
      - "@group(sources)"

  lint:
    command: cargo
    args: ["clippy", "--", "-D", "warnings"]
    deps:
      - "~:build"
    inputs:
      - "@group(configs)"
      - "@group(sources)"

  format-check:
    command: cargo
    args: ["fmt", "--check"]
    inputs:
      - "@group(configs)"
      - "@group(sources)"

  clean:
    script: >-
      cargo clean &&
      rm -f "$MOON_WORKSPACE_ROOT/.crates.toml" "$MOON_WORKSPACE_ROOT/.crates2.json"
    options:
      cache: false
